import { mkdir, writeFile } from "node:fs/promises";
import { extname, relative, resolve } from "node:path";
import type { ScannedRouteModule, ScannedRoutesResult } from "./route-manifest";

const PHIAL_TYPES_DIR = ".phial/types";
const MIDDLEWARE_TYPES_FILE = "middleware.d.ts";
const ROUTES_TYPES_FILE = "routes.d.ts";

export interface GeneratedPhialTypesResult {
  directory: string;
  middlewareFile: string;
  routesFile: string;
}

export async function writePhialProjectTypes(
  result: ScannedRoutesResult,
): Promise<GeneratedPhialTypesResult> {
  const typesDirectory = resolve(result.root, PHIAL_TYPES_DIR);
  const middlewareFile = resolve(typesDirectory, MIDDLEWARE_TYPES_FILE);
  const routesFile = resolve(typesDirectory, ROUTES_TYPES_FILE);

  await mkdir(typesDirectory, { recursive: true });
  await writeFile(middlewareFile, createMiddlewareTypesDeclaration(result), "utf8");
  await writeFile(routesFile, createRouteTypesDeclaration(result), "utf8");

  return {
    directory: typesDirectory,
    middlewareFile,
    routesFile,
  };
}

export function createMiddlewareTypesDeclaration(result: ScannedRoutesResult): string {
  const appMiddlewareNames = Object.keys(result.app.middleware).sort();
  const appEntries =
    appMiddlewareNames.length > 0
      ? appMiddlewareNames.map((name) => `    ${JSON.stringify(name)}: true`).join("\n")
      : "";

  return [
    "// Generated by Phial. Do not edit manually.",
    "declare module 'phial' {",
    "  interface MiddlewareRegistry {",
    ...(appEntries ? [appEntries] : []),
    "  }",
    "}",
    "",
    "export {}",
    "",
  ].join("\n");
}

export function createRouteTypesDeclaration(result: ScannedRoutesResult): string {
  const routes = collectTypedRoutes(result);
  const pathEntries =
    routes.length > 0
      ? collectPathRegistryEntries(routes)
          .map((route) => `    ${JSON.stringify(route.pathPattern)}: ${route.paramsType}`)
          .join("\n")
      : "";
  const targetPathUnion =
    routes.length > 0
      ? Array.from(new Set(routes.map((route) => route.targetPathType))).join(" | ")
      : "string";
  const idEntries =
    routes.length > 0
      ? routes
          .map(
            (route) =>
              `    ${JSON.stringify(route.id)}: { path: ${JSON.stringify(route.pathPattern)}; targetPath: ${route.targetPathType}; params: ${route.paramsType} }`,
          )
          .join("\n")
      : "";
  const appTypeImportLine = createAppDataTypeImportLine(result);
  const importTypeLines = createRouteTypeImportLines(routes);
  const loaderEntries =
    routes.length > 0
      ? routes
          .map(
            (route, index) =>
              `    ${JSON.stringify(route.id)}: ${createRouteDataTypeExpression(route, index, "loader")}`,
          )
          .join("\n")
      : "";
  const actionEntries =
    routes.length > 0
      ? routes
          .map(
            (route, index) =>
              `    ${JSON.stringify(route.id)}: ${createRouteDataTypeExpression(route, index, "action")}`,
          )
          .join("\n")
      : "";
  const appDataEntries = result.app.loader
    ? ['    data: ResolveRouteDataValue<ResolveRouteHandler<never, PhialAppLoaderModule, "loader">>']
    : [];

  return [
    "// Generated by Phial. Do not edit manually.",
    appTypeImportLine,
    appTypeImportLine ? "" : "",
    ...importTypeLines,
    importTypeLines.length > 0 ? "" : "",
    "declare module 'phial' {",
    "  interface AppDataRegistry {",
    ...appDataEntries,
    "  }",
    "",
    "  interface RoutePathRegistry {",
    ...(pathEntries ? [pathEntries] : []),
    "  }",
    "",
    "  interface RouteTypeRegistry {",
    `    targetPath: ${targetPathUnion}`,
    "  }",
    "",
    "  interface RouteIdRegistry {",
    ...(idEntries ? [idEntries] : []),
    "  }",
    "",
    "  interface RouteLoaderDataRegistry {",
    ...(loaderEntries ? [loaderEntries] : []),
    "  }",
    "",
    "  interface RouteActionDataRegistry {",
    ...(actionEntries ? [actionEntries] : []),
    "  }",
    "}",
    "",
    "export {}",
    "",
  ].join("\n");
}

function collectTypedRoutes(result: ScannedRoutesResult): Array<{
  id: string;
  module: ScannedRouteModule;
  pathPattern: string;
  targetPathType: string;
  paramsType: string;
}> {
  return result.modules
    .map((module) => {
      const route = createTypedRoute(result, module);
      return {
        id: module.id,
        module,
        pathPattern: route.pathPattern,
        targetPathType: route.targetPathType,
        paramsType: serializeParamsType(route.params),
      };
    })
    .sort((left, right) => left.id.localeCompare(right.id));
}

function collectPathRegistryEntries(
  routes: Array<{
    id: string;
    module: ScannedRouteModule;
    pathPattern: string;
    targetPathType: string;
    paramsType: string;
  }>,
): Array<{
  id: string;
  module: ScannedRouteModule;
  pathPattern: string;
  targetPathType: string;
  paramsType: string;
}> {
  const registry = new Map<
    string,
    {
      id: string;
      module: ScannedRouteModule;
      pathPattern: string;
      targetPathType: string;
      paramsType: string;
    }
  >();

  for (const route of routes) {
    if (!registry.has(route.pathPattern)) {
      registry.set(route.pathPattern, route);
    }
  }

  return [...registry.values()].sort((left, right) =>
    left.pathPattern.localeCompare(right.pathPattern),
  );
}

function createTypedRoute(
  result: ScannedRoutesResult,
  module: ScannedRouteModule,
): {
  pathPattern: string;
  targetPathType: string;
  params: Array<{ name: string; optional: boolean }>;
} {
  const relativeFile = toPosixPath(relative(result.routesDir, module.absoluteFile));
  const extension = extname(relativeFile);
  const withoutExtension = relativeFile.slice(0, -extension.length);
  const relativeDir = getEntryDirectory(withoutExtension);
  const segments = relativeDir ? relativeDir.split("/").filter(Boolean) : [];

  let variants: Array<{ segments: string[]; template: boolean }> = [
    { segments: [], template: false },
  ];
  const params: Array<{ name: string; optional: boolean }> = [];
  const patternSegments: string[] = [];

  for (const segment of segments) {
    if (isRouteGroup(segment)) {
      continue;
    }

    if (/^\[\[\.\.\.[^/]+\]\]$/.test(segment)) {
      const paramName = extractRouteParamName(segment);
      params.push({ name: paramName, optional: true });
      patternSegments.push(`:${paramName}`);
      variants = [
        ...variants,
        ...variants.map((variant) => ({
          segments: [...variant.segments, "${string}"],
          template: true,
        })),
      ];
      continue;
    }

    if (/^\[\.\.\.[^/]+\]$/.test(segment) || /^\[[^/]+\]$/.test(segment)) {
      const paramName = extractRouteParamName(segment);
      params.push({ name: paramName, optional: false });
      patternSegments.push(`:${paramName}`);
      variants = variants.map((variant) => ({
        segments: [...variant.segments, "${string}"],
        template: true,
      }));
      continue;
    }

    patternSegments.push(segment);
    variants = variants.map((variant) => ({
      segments: [...variant.segments, segment],
      template: variant.template,
    }));
  }

  const pathPattern = patternSegments.length > 0 ? `/${patternSegments.join("/")}` : "/";
  const targetPathType =
    variants.length > 0
      ? Array.from(
          new Set(
            variants.map((variant) => {
              if (variant.segments.length === 0) {
                return '"/"';
              }

              return variant.template
                ? `\`/${variant.segments.join("/")}\``
                : JSON.stringify(`/${variant.segments.join("/")}`);
            }),
          ),
        ).join(" | ")
      : "string";

  return {
    pathPattern,
    targetPathType,
    params,
  };
}

function createAppDataTypeImportLine(result: ScannedRoutesResult): string {
  if (!result.app.loader) {
    return "";
  }

  return `import type * as PhialAppLoaderModule from ${JSON.stringify(createTypeImportSpecifier(result.app.loader))}`;
}

function createRouteTypeImportLines(
  routes: Array<{
    id: string;
    module: ScannedRouteModule;
    pathPattern: string;
    targetPathType: string;
    paramsType: string;
  }>,
): string[] {
  return routes.flatMap((route, index) => {
    const lines: string[] = [
      `import type * as PhialRoutePrimaryModule${index} from ${JSON.stringify(createTypeImportSpecifier(route.module.file))}`,
    ];

    if (route.module.files.loader) {
      lines.push(
        `import type * as PhialRouteLoaderModule${index} from ${JSON.stringify(createTypeImportSpecifier(route.module.files.loader))}`,
      );
    }

    if (route.module.files.action) {
      lines.push(
        `import type * as PhialRouteActionModule${index} from ${JSON.stringify(createTypeImportSpecifier(route.module.files.action))}`,
      );
    }

    return lines;
  });
}

function createRouteDataTypeExpression(
  route: {
    module: ScannedRouteModule;
  },
  index: number,
  kind: "loader" | "action",
): string {
  const primaryModule = `PhialRoutePrimaryModule${index}`;
  const entryModule =
    kind === "loader"
      ? route.module.files.loader
        ? `PhialRouteLoaderModule${index}`
        : "never"
      : route.module.files.action
        ? `PhialRouteActionModule${index}`
        : "never";

  return `ResolveRouteDataValue<ResolveRouteHandler<${primaryModule}, ${entryModule}, ${JSON.stringify(kind)}>>`;
}

function serializeParamsType(params: Array<{ name: string; optional: boolean }>): string {
  if (params.length === 0) {
    return "{}";
  }

  return `{\n${params
    .map(({ name, optional }) => `  ${JSON.stringify(name)}${optional ? "?" : ""}: string`)
    .join(";\n")}\n}`;
}

function getEntryDirectory(path: string): string {
  const separatorIndex = path.lastIndexOf("/");
  return separatorIndex >= 0 ? path.slice(0, separatorIndex) : "";
}

function isRouteGroup(segment: string): boolean {
  return segment.startsWith("(") && segment.endsWith(")");
}

function extractRouteParamName(segment: string): string {
  return segment
    .replace(/^\[\[\.\.\.[^/]+/, "")
    .replace(/^\[\.\.\./, "")
    .replace(/^\[/, "")
    .replace(/\]\]?$/, "");
}

function createTypeImportSpecifier(file: string): string {
  return file.startsWith("/") ? file : `/${file}`;
}

function toPosixPath(path: string): string {
  return path.replace(/\\/g, "/");
}
