import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, test } from "vitest";

const repoRoot = resolve(import.meta.dirname, "..");
const exampleRoot = resolve(repoRoot, "examples/zero-config");

function readExampleFile(relativePath: string): string {
  return readFileSync(resolve(exampleRoot, relativePath), "utf8");
}

describe("zero-config example phial surface", () => {
  test("uses phial naming across source files, smoke scripts, and checked-in artifacts", () => {
    const phialConfigPath = resolve(exampleRoot, "phial.config.ts");
    const hornConfigPath = resolve(exampleRoot, "horn.config.ts");
    const phialTypecheckConfigPath = resolve(exampleRoot, ".phial/tsconfig.typecheck.json");
    const hornTypecheckConfigPath = resolve(exampleRoot, ".horn/tsconfig.typecheck.json");
    const phialMiddlewareTypesPath = resolve(exampleRoot, ".phial/types/middleware.d.ts");
    const hornMiddlewareTypesPath = resolve(exampleRoot, ".horn/types/middleware.d.ts");
    const phialRouteTypesPath = resolve(exampleRoot, ".phial/types/routes.d.ts");
    const hornRouteTypesPath = resolve(exampleRoot, ".horn/types/routes.d.ts");

    expect(existsSync(phialConfigPath)).toBe(true);
    expect(existsSync(hornConfigPath)).toBe(false);
    expect(existsSync(phialTypecheckConfigPath)).toBe(true);
    expect(existsSync(hornTypecheckConfigPath)).toBe(false);
    expect(existsSync(phialMiddlewareTypesPath)).toBe(true);
    expect(existsSync(hornMiddlewareTypesPath)).toBe(false);
    expect(existsSync(phialRouteTypesPath)).toBe(true);
    expect(existsSync(hornRouteTypesPath)).toBe(false);

    expect(readFileSync(phialConfigPath, "utf8")).toContain('from "phial/vite"');

    const readme = readExampleFile("README.md");
    expect(readme).toContain("`phial` app");
    expect(readme).toContain("`phial.config.ts`");
    expect(readme).toContain("From `repos/phial`:");
    expect(readme).toContain("pnpm exec tsx src/bin.ts prepare examples/zero-config");
    expect(readme).toContain("pnpm exec tsx src/bin.ts build examples/zero-config");
    expect(readme).toContain("pnpm exec tsx src/bin.ts start examples/zero-config");
    expect(readme).toContain("`phial prepare` writes `.phial/types/middleware.d.ts`");
    expect(readme).toContain("`.phial/types/routes.d.ts`");
    expect(readme).toContain("`ctx.request`");
    expect(readme).toContain("`ctx.get(...)`");
    expect(readme).toContain("`ctx.waitUntil(...)`");
    expect(readme).not.toContain("`horn` app");
    expect(readme).not.toContain("`horn.config.ts`");
    expect(readme).not.toContain("`.horn/types/");
    expect(readme).not.toContain("From `packages/phial`:");
    expect(readme).not.toContain("\nphial prepare\nphial build\nphial start\n");

    const homePageSource = readExampleFile("app/pages/index/page.ts");
    expect(homePageSource).not.toContain("this.data.value");
    expect(homePageSource).not.toContain("this.layoutData.value");
    expect(homePageSource).not.toContain("this.actionData.value");
    expect(homePageSource).not.toContain("this.layoutActionData.value");

    const blogPageSource = readExampleFile("app/pages/blog/[slug]/page.ts");
    expect(blogPageSource).not.toContain("this.data.value");
    expect(blogPageSource).not.toContain("this.route.value");

    const blogLoadingSource = readExampleFile("app/pages/blog/[slug]/loading.ts");
    expect(blogLoadingSource).toContain("route:");
    expect(blogLoadingSource).not.toContain("routeId:");
    expect(blogLoadingSource).not.toContain("location:");

    const rootLoadingSource = readExampleFile("app/pages/index/loading.ts");
    expect(rootLoadingSource).toContain("route:");
    expect(rootLoadingSource).not.toContain("routeId:");
    expect(rootLoadingSource).not.toContain("location:");
    expect(rootLoadingSource).not.toContain("previousLocation:");

    for (const relativePath of [
      "app/app.vue",
      "app/error.vue",
      "app/pages/layout.ts",
      "app/pages/index/page.ts",
      "app/pages/jsx/page.tsx",
      "app/pages/sfc/page.vue",
      "app/pages/blog/[slug]/page.ts",
    ]) {
      const source = readExampleFile(relativePath);
      if (relativePath === "app/error.vue") {
        expect(source).toContain('data-phial-error=""');
        expect(source).not.toContain("data-horn-error");
      } else if (
        relativePath === "app/app.vue" ||
        relativePath === "app/pages/jsx/page.tsx" ||
        relativePath === "app/pages/sfc/page.vue"
      ) {
        expect(source).toContain('from "phial/app"');
        expect(source).not.toContain('from "phial"');
      }
    }

    const middlewareTypes = readFileSync(phialMiddlewareTypesPath, "utf8");
    expect(middlewareTypes).toContain("// Generated by Phial. Do not edit manually.");
    expect(middlewareTypes).toContain("declare module 'phial' {");

    const routeTypes = readFileSync(phialRouteTypesPath, "utf8");
    expect(routeTypes).toContain("// Generated by Phial. Do not edit manually.");
    expect(routeTypes).toContain("declare module 'phial' {");

    const typecheckConfig = readFileSync(phialTypecheckConfigPath, "utf8");
    expect(typecheckConfig).toContain('"phial": [');
    expect(typecheckConfig).toContain('"phial/vite": [');
    expect(typecheckConfig).toContain('"../phial.config.ts"');
    expect(typecheckConfig).not.toContain("../horn.config.ts");

    const hmrSmoke = readFileSync(resolve(repoRoot, "scripts/hmr-smoke.mjs"), "utf8");
    expect(hmrSmoke).toContain('["exec", "tsx", "src/bin.ts"');
    expect(hmrSmoke).toContain("__phialHmrProbeLoads");
    expect(hmrSmoke).toContain("phial dev server:");
    expect(hmrSmoke).toContain("examples/zero-config/app/pages/index/page.ts");
    expect(hmrSmoke).not.toContain("examples/zero-config/app/pages/page.ts");
    expect(hmrSmoke).not.toContain("bin/horn.mjs");
    expect(hmrSmoke).not.toContain("__hornHmrProbeLoads");

    const serverRoutesSmoke = readFileSync(
      resolve(repoRoot, "scripts/server-routes-smoke.mjs"),
      "utf8",
    );
    expect(serverRoutesSmoke).toContain('["exec", "tsx", "src/bin.ts"');
    expect(serverRoutesSmoke).toContain(".phial/types/middleware.d.ts");
    expect(serverRoutesSmoke).toContain(".phial/types/routes.d.ts");
    expect(serverRoutesSmoke).toContain(".phial/tsconfig.typecheck.json");
    expect(serverRoutesSmoke).toContain("declare module 'phial' {");
    expect(serverRoutesSmoke).not.toContain("createExampleTypecheckConfigSource");
    expect(serverRoutesSmoke).not.toContain('writeFile(typecheckConfigFile');
    expect(serverRoutesSmoke).not.toContain("bin/horn.mjs");
    expect(serverRoutesSmoke).not.toContain(".horn/");
    expect(serverRoutesSmoke).not.toContain("../horn.config.ts");

    const serverBundle = readExampleFile(".output/server/index.js");
    expect(serverBundle).toContain("phial/generated-app-plugin");
    expect(serverBundle).toContain("phial/generated-server-plugin");
    expect(serverBundle).toContain("virtual:phial-server-entry");
    expect(serverBundle).toContain("data-phial-error");
    expect(serverBundle).not.toContain("data-horn-error");
    expect(serverBundle).not.toContain("virtual:horn/");
  });
});
