import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, test } from "vitest";

const repoRoot = resolve(import.meta.dirname, "..");
const exampleRoot = resolve(repoRoot, "examples/zero-config");

function readExampleFile(relativePath: string): string {
  return readFileSync(resolve(exampleRoot, relativePath), "utf8");
}

describe("zero-config example vuloom surface", () => {
  test("uses vuloom naming across source files, smoke scripts, and checked-in artifacts", () => {
    const vuloomConfigPath = resolve(exampleRoot, "vuloom.config.ts");
    const hornConfigPath = resolve(exampleRoot, "horn.config.ts");
    const vuloomTypecheckConfigPath = resolve(exampleRoot, ".vuloom/tsconfig.typecheck.json");
    const hornTypecheckConfigPath = resolve(exampleRoot, ".horn/tsconfig.typecheck.json");
    const vuloomMiddlewareTypesPath = resolve(exampleRoot, ".vuloom/types/middleware.d.ts");
    const hornMiddlewareTypesPath = resolve(exampleRoot, ".horn/types/middleware.d.ts");
    const vuloomRouteTypesPath = resolve(exampleRoot, ".vuloom/types/routes.d.ts");
    const hornRouteTypesPath = resolve(exampleRoot, ".horn/types/routes.d.ts");

    expect(existsSync(vuloomConfigPath)).toBe(true);
    expect(existsSync(hornConfigPath)).toBe(false);
    expect(existsSync(vuloomTypecheckConfigPath)).toBe(true);
    expect(existsSync(hornTypecheckConfigPath)).toBe(false);
    expect(existsSync(vuloomMiddlewareTypesPath)).toBe(true);
    expect(existsSync(hornMiddlewareTypesPath)).toBe(false);
    expect(existsSync(vuloomRouteTypesPath)).toBe(true);
    expect(existsSync(hornRouteTypesPath)).toBe(false);

    expect(readFileSync(vuloomConfigPath, "utf8")).toContain('from "vuloom/vite"');

    const readme = readExampleFile("README.md");
    expect(readme).toContain("`vuloom` app");
    expect(readme).toContain("`vuloom.config.ts`");
    expect(readme).toContain("From `repos/vuloom`:");
    expect(readme).toContain("pnpm exec tsx src/bin.ts prepare examples/zero-config");
    expect(readme).toContain("pnpm exec tsx src/bin.ts build examples/zero-config");
    expect(readme).toContain("pnpm exec tsx src/bin.ts start examples/zero-config");
    expect(readme).toContain("`vuloom prepare` writes `.vuloom/types/middleware.d.ts`");
    expect(readme).toContain("`.vuloom/types/routes.d.ts`");
    expect(readme).toContain("`ctx.request`");
    expect(readme).toContain("`ctx.get(...)`");
    expect(readme).toContain("`ctx.waitUntil(...)`");
    expect(readme).not.toContain("`horn` app");
    expect(readme).not.toContain("`horn.config.ts`");
    expect(readme).not.toContain("`.horn/types/");
    expect(readme).not.toContain("From `packages/vuloom`:");
    expect(readme).not.toContain("\nvuloom prepare\nvuloom build\nvuloom start\n");

    const homePageSource = readExampleFile("app/pages/index/page.ts");
    expect(homePageSource).not.toContain("this.data.value");
    expect(homePageSource).not.toContain("this.layoutData.value");
    expect(homePageSource).not.toContain("this.actionData.value");
    expect(homePageSource).not.toContain("this.layoutActionData.value");

    const blogPageSource = readExampleFile("app/pages/blog/[slug]/page.ts");
    expect(blogPageSource).not.toContain("this.data.value");
    expect(blogPageSource).not.toContain("this.route.value");

    const blogLoadingSource = readExampleFile("app/pages/blog/[slug]/loading.ts");
    expect(blogLoadingSource).toContain("route:");
    expect(blogLoadingSource).not.toContain("routeId:");
    expect(blogLoadingSource).not.toContain("location:");

    const rootLoadingSource = readExampleFile("app/pages/index/loading.ts");
    expect(rootLoadingSource).toContain("route:");
    expect(rootLoadingSource).not.toContain("routeId:");
    expect(rootLoadingSource).not.toContain("location:");
    expect(rootLoadingSource).not.toContain("previousLocation:");

    for (const relativePath of [
      "app/app.vue",
      "app/error.vue",
      "app/pages/layout.ts",
      "app/pages/index/page.ts",
      "app/pages/jsx/page.tsx",
      "app/pages/sfc/page.vue",
      "app/pages/blog/[slug]/page.ts",
    ]) {
      const source = readExampleFile(relativePath);
      if (relativePath === "app/error.vue") {
        expect(source).toContain('data-vuloom-error=""');
        expect(source).not.toContain("data-horn-error");
      } else if (
        relativePath === "app/app.vue" ||
        relativePath === "app/pages/jsx/page.tsx" ||
        relativePath === "app/pages/sfc/page.vue"
      ) {
        expect(source).toContain('from "vuloom/app"');
        expect(source).not.toContain('from "vuloom"');
      }
    }

    const middlewareTypes = readFileSync(vuloomMiddlewareTypesPath, "utf8");
    expect(middlewareTypes).toContain("// Generated by Vuloom. Do not edit manually.");
    expect(middlewareTypes).toContain("declare module 'vuloom' {");

    const routeTypes = readFileSync(vuloomRouteTypesPath, "utf8");
    expect(routeTypes).toContain("// Generated by Vuloom. Do not edit manually.");
    expect(routeTypes).toContain("declare module 'vuloom' {");

    const typecheckConfig = readFileSync(vuloomTypecheckConfigPath, "utf8");
    expect(typecheckConfig).toContain('"vuloom": [');
    expect(typecheckConfig).toContain('"vuloom/vite": [');
    expect(typecheckConfig).toContain('"../vuloom.config.ts"');
    expect(typecheckConfig).not.toContain("../horn.config.ts");

    const hmrSmoke = readFileSync(resolve(repoRoot, "scripts/hmr-smoke.mjs"), "utf8");
    expect(hmrSmoke).toContain('["exec", "tsx", "src/bin.ts"');
    expect(hmrSmoke).toContain("__vuloomHmrProbeLoads");
    expect(hmrSmoke).toContain("vuloom dev server:");
    expect(hmrSmoke).toContain("examples/zero-config/app/pages/index/page.ts");
    expect(hmrSmoke).not.toContain("examples/zero-config/app/pages/page.ts");
    expect(hmrSmoke).not.toContain("bin/horn.mjs");
    expect(hmrSmoke).not.toContain("__hornHmrProbeLoads");

    const serverRoutesSmoke = readFileSync(
      resolve(repoRoot, "scripts/server-routes-smoke.mjs"),
      "utf8",
    );
    expect(serverRoutesSmoke).toContain('["exec", "tsx", "src/bin.ts"');
    expect(serverRoutesSmoke).toContain(".vuloom/types/middleware.d.ts");
    expect(serverRoutesSmoke).toContain(".vuloom/types/routes.d.ts");
    expect(serverRoutesSmoke).toContain(".vuloom/tsconfig.typecheck.json");
    expect(serverRoutesSmoke).toContain("declare module 'vuloom' {");
    expect(serverRoutesSmoke).not.toContain("createExampleTypecheckConfigSource");
    expect(serverRoutesSmoke).not.toContain('writeFile(typecheckConfigFile');
    expect(serverRoutesSmoke).not.toContain("bin/horn.mjs");
    expect(serverRoutesSmoke).not.toContain(".horn/");
    expect(serverRoutesSmoke).not.toContain("../horn.config.ts");

    const serverBundle = readExampleFile(".output/server/index.js");
    expect(serverBundle).toContain("vuloom/generated-app-plugin");
    expect(serverBundle).toContain("vuloom/generated-server-plugin");
    expect(serverBundle).toContain("virtual:vuloom-server-entry");
    expect(serverBundle).toContain("data-vuloom-error");
    expect(serverBundle).not.toContain("data-horn-error");
    expect(serverBundle).not.toContain("virtual:horn/");
  });
});
