// Generated by nitro

// App Config
import type { Defu } from 'defu'

import type { default as appConfig0 } from "../../../../node_modules/.pnpm/undocs@0.4.16_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@e_2d315543fc63d82b1fb0ec495115132c/node_modules/undocs/app/app.config";

type UserAppConfig = Defu<{}, [typeof appConfig0]>

declare module "nitropack/types" {
  interface AppConfig extends UserAppConfig {}

}
export {}