// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/raw/**:slug.md': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/undocs@0.4.16_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@e_2d315543fc63d82b1fb0ec495115132c/node_modules/undocs/app/server/routes/raw/[...slug].md.get').default>>>>
      'GET': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+content@3.13.0_better-sqlite3@12.9.0_magicast@0.5.2/node_modules/@nuxt/content/dist/features/llms/runtime/server/routes/raw/[...slug].md.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+nitro-server@4.4.2_@babel+core@7.29.0_better-sqlite3@12.9.0_db0@0.3.4_better-sqli_897a80594fdcccadc0a9d9e45ce8c65f/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/_og/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/undocs@0.4.16_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@e_2d315543fc63d82b1fb0ec495115132c/node_modules/undocs/app/modules/og-image/runtime/handler').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+icon@2.2.1_magicast@0.5.2_vite@8.0.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@ty_cf7bad10cccd03a1480f28fac8f533ad/node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/__nuxt_content/content/sql_dump.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+content@3.13.0_better-sqlite3@12.9.0_magicast@0.5.2/node_modules/@nuxt/content/dist/runtime/presets/node/database-handler').default>>>>
    }
    '/__nuxt_content/info/sql_dump.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+content@3.13.0_better-sqlite3@12.9.0_magicast@0.5.2/node_modules/@nuxt/content/dist/runtime/presets/node/database-handler').default>>>>
    }
    '/__nuxt_content/content/query': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+content@3.13.0_better-sqlite3@12.9.0_magicast@0.5.2/node_modules/@nuxt/content/dist/runtime/api/query.post').default>>>>
    }
    '/__nuxt_content/info/query': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+content@3.13.0_better-sqlite3@12.9.0_magicast@0.5.2/node_modules/@nuxt/content/dist/runtime/api/query.post').default>>>>
    }
  }
}
export {}