import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { afterEach, describe, expect, test } from "vitest";
import {
  createMiddlewareTypesDeclaration,
  createRouteManifest,
  createRouteTypesDeclaration,
  writeVuloomProjectTypes,
  type ScannedRoutesResult,
} from "../../../src/lib/vite/scanners/index.ts";

const tempRoots: string[] = [];

afterEach(async () => {
  for (const root of tempRoots.splice(0)) {
    await rm(root, { recursive: true, force: true });
  }
});

const scannedResult: ScannedRoutesResult = {
  root: "/repo",
  appDir: "/repo/app",
  routesDir: "/repo/app/pages",
  serverRoutesDir: "/repo/server/routes",
  serverMiddlewareDir: "/repo/server/middleware",
  app: {
    app: "app/app.vue",
    error: "app/error.vue",
    loader: "app/loader.ts",
    middleware: {
      auth: "app/middleware/auth.ts",
    },
  },
  server: {
    routesDir: "server/routes",
    middlewareDir: "server/middleware",
    routes: [],
    middleware: {
      trace: "server/middleware/trace.ts",
    },
  },
  modules: [
    {
      id: "posts/[slug]/page",
      kind: "page",
      file: "app/pages/posts/[slug]/page.vue",
      absoluteFile: "/repo/app/pages/posts/[slug]/page.vue",
      directoryMiddleware: [],
      path: ":slug",
      parentId: "layout",
      files: {
        page: "app/pages/posts/[slug]/page.vue",
        loader: "app/pages/posts/[slug]/loader.ts",
        action: "app/pages/posts/[slug]/action.ts",
      },
    },
  ],
  manifest: [],
};

scannedResult.manifest = createRouteManifest(scannedResult.modules);

describe("types-generator", () => {
  test("creates middleware declaration", () => {
    const output = createMiddlewareTypesDeclaration(scannedResult);

    expect(output).toContain("// Generated by Vuloom. Do not edit manually.");
    expect(output).toContain("declare module 'vuloom'");
    expect(output).toContain('"auth": true');
    expect(output).not.toContain("ServerMiddlewareRegistry");
  });

  test("creates route declaration", () => {
    const output = createRouteTypesDeclaration(scannedResult);

    expect(output).toContain("// Generated by Vuloom. Do not edit manually.");
    expect(output).toContain("interface RoutePathRegistry");
    expect(output).toContain('"/posts/:slug"');
    expect(output).toContain('"posts/[slug]/page"');
    expect(output).toContain("declare module 'vuloom'");
    expect(output).toContain("VuloomRoutePrimaryModule0");
    expect(output).toContain("VuloomRouteLoaderModule0");
    expect(output).toContain("VuloomRouteActionModule0");
  });

  test("writes generated type files into .vuloom/types", async () => {
    const root = await mkdtemp(join(tmpdir(), "vuloom-types-generator-"));
    tempRoots.push(root);
    const result = {
      ...scannedResult,
      root,
      appDir: resolve(root, "app"),
      routesDir: resolve(root, "app/pages"),
      serverRoutesDir: resolve(root, "server/routes"),
      serverMiddlewareDir: resolve(root, "server/middleware"),
    } satisfies ScannedRoutesResult;

    const written = await writeVuloomProjectTypes(result);

    expect(written.directory).toBe(resolve(root, ".vuloom/types"));
    expect(written.middlewareFile).toBe(resolve(root, ".vuloom/types/middleware.d.ts"));
    expect(written.routesFile).toBe(resolve(root, ".vuloom/types/routes.d.ts"));
    await expect(readFile(written.routesFile, "utf8")).resolves.toContain("declare module 'vuloom'");
  });
});
