export { useScriptTriggerConsent, useScriptEventPage, useScriptTriggerElement, useScript, useScriptGoogleAnalytics, useScriptPlausibleAnalytics, useScriptCrisp, useScriptClarity, useScriptCloudflareWebAnalytics, useScriptFathomAnalytics, useScriptMatomoAnalytics, useScriptGoogleTagManager, useScriptGoogleAdsense, useScriptSegment, useScriptMetaPixel, useScriptXPixel, useScriptIntercom, useScriptHotjar, useScriptStripe, useScriptLemonSqueezy, useScriptVimeoPlayer, useScriptYouTubePlayer, useScriptGoogleMaps, useScriptNpm, useScriptUmamiAnalytics, useScriptSnapchatPixel, useScriptRybbitAnalytics, useScriptDatabuddyAnalytics, useScriptRedditPixel, useScriptPayPal } from '#app/composables/script-stubs';
export { isVue2, isVue3 } from 'vue-demi';
export { defineNuxtLink } from '#app/components/nuxt-link';
export { useNuxtApp, tryUseNuxtApp, defineNuxtPlugin, definePayloadPlugin, useRuntimeConfig, defineAppConfig } from '#app/nuxt';
export { useAppConfig, updateAppConfig } from '#app/config';
export { defineNuxtComponent } from '#app/composables/component';
export { useAsyncData, useLazyAsyncData, useNuxtData, refreshNuxtData, clearNuxtData, createUseAsyncData } from '#app/composables/asyncData';
export { useHydration } from '#app/composables/hydrate';
export { callOnce } from '#app/composables/once';
export { useState, clearNuxtState } from '#app/composables/state';
export { clearError, createError, isNuxtError, showError, useError } from '#app/composables/error';
export { useFetch, useLazyFetch, createUseFetch } from '#app/composables/fetch';
export { useCookie, refreshCookie } from '#app/composables/cookie';
export { onPrehydrate, prerenderRoutes, useRequestHeader, useRequestHeaders, useResponseHeader, useRequestEvent, useRequestFetch, setResponseStatus } from '#app/composables/ssr';
export { onNuxtReady } from '#app/composables/ready';
export { preloadComponents, prefetchComponents, preloadRouteComponents } from '#app/composables/preload';
export { abortNavigation, addRouteMiddleware, defineNuxtRouteMiddleware, setPageLayout, navigateTo, useRoute, useRouter } from '#app/composables/router';
export { isPrerendered, loadPayload, preloadPayload, definePayloadReducer, definePayloadReviver } from '#app/composables/payload';
export { useLoadingIndicator } from '#app/composables/loading-indicator';
export { getAppManifest, getRouteRules } from '#app/composables/manifest';
export { reloadNuxtApp } from '#app/composables/chunk';
export { useRequestURL } from '#app/composables/url';
export { usePreviewMode } from '#app/composables/preview';
export { useRouteAnnouncer } from '#app/composables/route-announcer';
export { useAnnouncer } from '#app/composables/announcer';
export { useRuntimeHook } from '#app/composables/runtime-hook';
export { useHead, useHeadSafe, useServerHeadSafe, useServerHead, useSeoMeta, useServerSeoMeta, injectHead } from '#app/composables/head';
export { onBeforeRouteLeave, onBeforeRouteUpdate, useLink } from 'vue-router';
export { withCtx, withDirectives, withKeys, withMemo, withModifiers, withScopeId, onActivated, onBeforeMount, onBeforeUnmount, onBeforeUpdate, onDeactivated, onErrorCaptured, onMounted, onRenderTracked, onRenderTriggered, onServerPrefetch, onUnmounted, onUpdated, computed, customRef, isProxy, isReactive, isReadonly, isRef, markRaw, proxyRefs, reactive, readonly, ref, shallowReactive, shallowReadonly, shallowRef, toRaw, toRef, toRefs, triggerRef, unref, watch, watchEffect, watchPostEffect, watchSyncEffect, onWatcherCleanup, isShallow, effect, effectScope, getCurrentScope, onScopeDispose, defineComponent, defineAsyncComponent, resolveComponent, getCurrentInstance, h, inject, hasInjectionContext, nextTick, provide, toValue, useModel, useAttrs, useCssModule, useSlots, useTransitionState, useId, useTemplateRef, useShadowRoot, useCssVars, Component, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue';
export { requestIdleCallback, cancelIdleCallback } from '#app/compat/idle-callback';
export { setInterval } from '#app/compat/interval';
export { definePageMeta, PageMeta } from '#app/composables/pages';
export { defineLazyHydrationComponent } from '#app/composables/lazy-hydration';
export { useContributors, Contributor } from '../../../node_modules/.pnpm/undocs@0.4.16_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@e_2d315543fc63d82b1fb0ec495115132c/node_modules/undocs/app/composables/useContributors';
export { useDocsNav } from '../../../node_modules/.pnpm/undocs@0.4.16_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@e_2d315543fc63d82b1fb0ec495115132c/node_modules/undocs/app/composables/useDocsNav';
export { useMermaid } from '../../../node_modules/.pnpm/undocs@0.4.16_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@e_2d315543fc63d82b1fb0ec495115132c/node_modules/undocs/app/composables/useMermaid';
export { usePageSEO } from '../../../node_modules/.pnpm/undocs@0.4.16_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@e_2d315543fc63d82b1fb0ec495115132c/node_modules/undocs/app/composables/usePageSEO';
export { useSponsors, Sponsors } from '../../../node_modules/.pnpm/undocs@0.4.16_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@e_2d315543fc63d82b1fb0ec495115132c/node_modules/undocs/app/composables/useSponsors';
export { formatNumber } from '../../../node_modules/.pnpm/undocs@0.4.16_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@e_2d315543fc63d82b1fb0ec495115132c/node_modules/undocs/app/utils/numbers';
export { packageManagers } from '../../../node_modules/.pnpm/undocs@0.4.16_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@e_2d315543fc63d82b1fb0ec495115132c/node_modules/undocs/app/utils/pm';
export { titleCase } from '../../../node_modules/.pnpm/undocs@0.4.16_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@e_2d315543fc63d82b1fb0ec495115132c/node_modules/undocs/app/utils/title';
export { defineLocale, extendLocale } from '../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@nuxt+content@3.13.0_better-sqlite3@12.9.0_magicast@0.5.2__@tiptap+exten_fb445b397b8e0836c8f9afb0fc5368db/node_modules/@nuxt/ui/dist/runtime/composables/defineLocale';
export { defineShortcuts, extractShortcuts } from '../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@nuxt+content@3.13.0_better-sqlite3@12.9.0_magicast@0.5.2__@tiptap+exten_fb445b397b8e0836c8f9afb0fc5368db/node_modules/@nuxt/ui/dist/runtime/composables/defineShortcuts';
export { useContentSearch } from '../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@nuxt+content@3.13.0_better-sqlite3@12.9.0_magicast@0.5.2__@tiptap+exten_fb445b397b8e0836c8f9afb0fc5368db/node_modules/@nuxt/ui/dist/runtime/composables/useContentSearch';
export { useFileUpload } from '../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@nuxt+content@3.13.0_better-sqlite3@12.9.0_magicast@0.5.2__@tiptap+exten_fb445b397b8e0836c8f9afb0fc5368db/node_modules/@nuxt/ui/dist/runtime/composables/useFileUpload';
export { useFormField } from '../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@nuxt+content@3.13.0_better-sqlite3@12.9.0_magicast@0.5.2__@tiptap+exten_fb445b397b8e0836c8f9afb0fc5368db/node_modules/@nuxt/ui/dist/runtime/composables/useFormField';
export { useKbd } from '../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@nuxt+content@3.13.0_better-sqlite3@12.9.0_magicast@0.5.2__@tiptap+exten_fb445b397b8e0836c8f9afb0fc5368db/node_modules/@nuxt/ui/dist/runtime/composables/useKbd';
export { useOverlay } from '../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@nuxt+content@3.13.0_better-sqlite3@12.9.0_magicast@0.5.2__@tiptap+exten_fb445b397b8e0836c8f9afb0fc5368db/node_modules/@nuxt/ui/dist/runtime/composables/useOverlay';
export { useResizable } from '../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@nuxt+content@3.13.0_better-sqlite3@12.9.0_magicast@0.5.2__@tiptap+exten_fb445b397b8e0836c8f9afb0fc5368db/node_modules/@nuxt/ui/dist/runtime/composables/useResizable';
export { useScrollShadow } from '../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@nuxt+content@3.13.0_better-sqlite3@12.9.0_magicast@0.5.2__@tiptap+exten_fb445b397b8e0836c8f9afb0fc5368db/node_modules/@nuxt/ui/dist/runtime/composables/useScrollShadow';
export { useScrollspy } from '../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@nuxt+content@3.13.0_better-sqlite3@12.9.0_magicast@0.5.2__@tiptap+exten_fb445b397b8e0836c8f9afb0fc5368db/node_modules/@nuxt/ui/dist/runtime/composables/useScrollspy';
export { useToast } from '../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@nuxt+content@3.13.0_better-sqlite3@12.9.0_magicast@0.5.2__@tiptap+exten_fb445b397b8e0836c8f9afb0fc5368db/node_modules/@nuxt/ui/dist/runtime/composables/useToast';
export { queryCollection, queryCollectionSearchSections, queryCollectionNavigation, queryCollectionItemSurroundings } from '../../../node_modules/.pnpm/@nuxt+content@3.13.0_better-sqlite3@12.9.0_magicast@0.5.2/node_modules/@nuxt/content/dist/runtime/client';
export { useColorMode } from '../../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.5.2/node_modules/@nuxtjs/color-mode/dist/runtime/composables';
export { flatUnwrap as unwrapSlot } from '../../../node_modules/.pnpm/@nuxtjs+mdc@0.21.1_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/utils/node';
export { parseMarkdown } from '../../../node_modules/.pnpm/@nuxtjs+mdc@0.21.1_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/parser';
export { stringifyMarkdown } from '../../../node_modules/.pnpm/@nuxtjs+mdc@0.21.1_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/stringify';