// Generated by Phial. Do not edit manually.
import type * as PhialAppLoaderModule from "/app/loader.ts"

import type * as PhialRoutePrimaryModule0 from "/app/pages/blog/[slug]/page.ts"
import type * as PhialRouteLoaderModule0 from "/app/pages/blog/[slug]/loader.ts"
import type * as PhialRoutePrimaryModule1 from "/app/pages/jsx/page.tsx"
import type * as PhialRoutePrimaryModule2 from "/app/pages/layout.ts"
import type * as PhialRouteLoaderModule2 from "/app/pages/loader.ts"
import type * as PhialRouteActionModule2 from "/app/pages/action.ts"
import type * as PhialRoutePrimaryModule3 from "/app/pages/page.ts"
import type * as PhialRoutePrimaryModule4 from "/app/pages/sfc/page.vue"

declare module 'phial' {
  interface AppDataRegistry {
    data: ResolveRouteDataValue<ResolveRouteHandler<never, PhialAppLoaderModule, "loader">>
  }

  interface RoutePathRegistry {
    "/": {}
    "/blog/:slug": {
  "slug": string
}
    "/jsx": {}
    "/sfc": {}
  }

  interface RouteTypeRegistry {
    targetPath: `/blog/${string}` | "/jsx" | "/" | "/sfc"
  }

  interface RouteIdRegistry {
    "blog/[slug]/page": { path: "/blog/:slug"; targetPath: `/blog/${string}`; params: {
  "slug": string
} }
    "jsx/page": { path: "/jsx"; targetPath: "/jsx"; params: {} }
    "layout": { path: "/"; targetPath: "/"; params: {} }
    "page": { path: "/"; targetPath: "/"; params: {} }
    "sfc/page": { path: "/sfc"; targetPath: "/sfc"; params: {} }
  }

  interface RouteLoaderDataRegistry {
    "blog/[slug]/page": ResolveRouteDataValue<ResolveRouteHandler<PhialRoutePrimaryModule0, PhialRouteLoaderModule0, "loader">>
    "jsx/page": ResolveRouteDataValue<ResolveRouteHandler<PhialRoutePrimaryModule1, never, "loader">>
    "layout": ResolveRouteDataValue<ResolveRouteHandler<PhialRoutePrimaryModule2, PhialRouteLoaderModule2, "loader">>
    "page": ResolveRouteDataValue<ResolveRouteHandler<PhialRoutePrimaryModule3, never, "loader">>
    "sfc/page": ResolveRouteDataValue<ResolveRouteHandler<PhialRoutePrimaryModule4, never, "loader">>
  }

  interface RouteActionDataRegistry {
    "blog/[slug]/page": ResolveRouteDataValue<ResolveRouteHandler<PhialRoutePrimaryModule0, never, "action">>
    "jsx/page": ResolveRouteDataValue<ResolveRouteHandler<PhialRoutePrimaryModule1, never, "action">>
    "layout": ResolveRouteDataValue<ResolveRouteHandler<PhialRoutePrimaryModule2, PhialRouteActionModule2, "action">>
    "page": ResolveRouteDataValue<ResolveRouteHandler<PhialRoutePrimaryModule3, never, "action">>
    "sfc/page": ResolveRouteDataValue<ResolveRouteHandler<PhialRoutePrimaryModule4, never, "action">>
  }
}

export {}
